apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
{{ include "synapse.labels" . | indent 4 }}
type: Opaque
data:
  homeserver.yaml: {{ .Values.homeserver | toYaml | b64enc | quote }}
  log.config: {{ .Values.logconfig | toYaml | b64enc | quote }}
