{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synapse.serviceAccountName" . }}
  labels:
{{ include "synapse.labels" . | indent 4 }}
{{- end -}}
